spring:
  application:
    name: book-service
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?createDatabaseIfNotExist=true
    username: root
    password: 1111
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
    eureka:
      client:
        register-with-eureka: true
        fetch-registry: true
server:
  port: 8082